image: gcc:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

# Build stage
build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y cmake python3 python3-pip lcov gcovr
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make

# Test stage
test:
  stage: test
  script:
    - cd build
    - ctest --output-on-failure